name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI (Fixed Version)
        run: |
          SUPABASE_LATEST=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget https://github.com/supabase/cli/releases/download/${SUPABASE_LATEST}/supabase-linux-amd64 -O supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/
          supabase --version

      - name: Deploy Supabase Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref iaojakycqyvboxbhlmjz
          supabase functions deploy extract_text --no-verify-jwt
