name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI (Fixed URL)
        run: |
          wget https://github.com/supabase/cli/releases/download/v2.12.0/supabase_linux_amd64.tar.gz -O supabase.tar.gz
          tar -xzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/
          supabase --version

      - name: Deploy Supabase Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref iaojakycqyvboxbhlmjz
          supabase functions deploy extract_text --no-verify-jwt
